services:
    app:
        build:
            args:
                user: leonardo
                uid: 1000
            context: ./
            dockerfile: DockerFile
        container_name: docker-php
        image: app-laravel
        volumes:
            - ./:/var/www
        restart: unless-stopped
        depends_on:
            - redis
        networks:
            - docker-laravel

    nginx:
        container_name: docker-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
        - "80:80"
        volumes: 
        - ./:/var/www
        - ./nginx:/etc/nginx/conf.d/
        networks: 
        - docker-laravel

    mysql:
        container_name: docker-mysql
        image: mysql:latest
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes: 
            - ./:/var/www
            - ./mysql:/var/lib/mysql
        ports: 
        - 3307:3306
        networks: 
            - docker-laravel

    redis:
      container_name: docker-redis
      image: redis:alpine
      networks:
          - docker-laravel

    queue:
        build:
            args:
                user: leonardo
                uid: 1000
            context: ./
            dockerfile: DockerFile
        container_name: docker-queue
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - docker-laravel


networks:
    docker-laravel:
        driver: bridge